---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
vip: '192.168.1.103'
haproxy_frontend_port: 6443 
haproxy_frontend_mode: 'tcp'

# Backend settings.
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'tcp'
haproxy_backend_balance_method: 'roundrobin'
#haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

# List of backend servers.
haproxy_backend_servers:
 - name: master-1
   address: 172.16.77.201:6443
 - name: master-2
   address: 172.16.77.202:6443
 - name: master-3
   address: 172.16.77.203:6443
# Extra global vars (see README for example usage).
haproxy_global_vars: []
