apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-goweb
spec:
  podSelector:
    matchLabels:
      run: goweb
  ingress:
  - from:
    - podSelector:
        matchLabels:
          clientGoweb: "true"