# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  N = 2

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory =  512 
  end
  (1..N).each do |machine_id|

    config.vm.define "haproxy-#{machine_id}" do |machine|
      machine.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub" 
      machine.vm.provision "shell", inline: "cat ~vagrant/.ssh/me.pub >> ~vagrant/.ssh/authorized_keys"
      machine.vm.hostname = "haproxy-#{machine_id}"
      machine.vm.network "private_network", ip: "172.16.77.#{2+machine_id}"
      machine.vm.network "public_network", bridge: "wlp59s0", ip: "192.168.1.10#{+machine_id}"
      machine.vm.network "forwarded_port", guest: 22, host: "22#{2+machine_id}"
      machine.vm.network "forwarded_port", guest: 6443, host: "64#{4+machine_id}"

    end
  end
end
