# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"
  N = 3

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048 
  end
  (1..N).each do |machine_id|

    config.vm.define "master-#{machine_id}" do |machine|
      machine.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub" 
      machine.vm.provision "shell", inline: "cat ~vagrant/.ssh/me.pub >> ~vagrant/.ssh/authorized_keys" 
      machine.vm.hostname = "master-#{machine_id}"
      machine.vm.network "private_network", ip: "172.16.77.20#{+machine_id}"
      machine.vm.network "public_network", bridge: "wlp59s0", ip: "192.168.1.20#{+machine_id}"
      machine.vm.network "forwarded_port", guest: 22, host: "24#{2+machine_id}"
      machine.vm.network "forwarded_port", guest: 6443, host: "65#{4+machine_id}"

    end
  end
end
